displayName=Revenant Ether Counter
author=Hazel St
description=This RuneLite plugin continues to count revenant ether after reaching the maximum of 65535 total ether on the collection log
tags=
version=
plugins=dev.lps.RevenantEtherTrackerPlugin
build=standard
