displayName=Revenant Ether Loot Tracker
author=Hazel St
description=This RuneLite plugin continues to count revenant ether even after reaching the maximum of 65535 total ether on the collection log!
tags=revenants,revs,ether,tracker
version=
plugins=dev.lps.RevenantEtherLootTrackerPlugin
build=standard
support=https://github.com/lps-dot-dev/revenant-ether-loot-tracker
